resolver: lts-10.4
extra-deps:
- git: git@github.com:rcook/codeworld-account.git
  commit: 18d87fd0e2bcf3abbacafc4936887e74579f8a8f
- git: git@github.com:rcook/codeworld-auth.git
  commit: 805cc2de1b1bdeb171983c75653ba557042a1bd8
- jwt-0.8.0
